import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import {
  existsSync,
  cpSync,
  mkdirSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "fs";
import type { Plugin } from "vite";
import runtimeErrorOverlay from "@replit/vite-plugin-runtime-error-modal";

const rawPort = process.env.PORT ?? "5173";
const port = Number(rawPort);

if (Number.isNaN(port) || port <= 0) {
  throw new Error(`Invalid PORT value: "${rawPort}"`);
}

const basePath = process.env.BASE_PATH ?? "/";

/** Names under `games/` that are not package-id folders */
const GAMES_NON_GAME_DIRS = new Set(["categories"]);

function writeGameIdsManifest(rootDir: string): void {
  const gamesDir = path.resolve(rootDir, "games");
  const ids: string[] = [];
  if (existsSync(gamesDir)) {
    for (const name of readdirSync(gamesDir)) {
      if (GAMES_NON_GAME_DIRS.has(name)) continue;
      const p = path.join(gamesDir, name);
      try {
        if (statSync(p).isDirectory()) ids.push(name);
      } catch {
        /* ignore */
      }
    }
  }
  ids.sort();
  const outDir = path.join(rootDir, "src", "generated");
  mkdirSync(outDir, { recursive: true });
  const lines = [
    "/* auto-generated by Vite — do not edit */",
    `export const GAME_IDS_WITH_LOCAL_ASSETS = new Set<string>([${ids.map((id) => JSON.stringify(id)).join(", ")}]);`,
    "",
  ];
  writeFileSync(path.join(outDir, "game-asset-ids.ts"), lines.join("\n"), "utf8");
}

/**
 * Root `games/` is the source of truth. Vite only serves static files from `public/`,
 * so we mirror `games` → `public/games` before dev (and on file changes) so `/games/...` resolves.
 * Production: `closeBundle` copies root `games` → `dist/public/games`.
 */
function syncRootGamesToPublic(rootDir: string): void {
  const src = path.resolve(rootDir, "games");
  const dest = path.resolve(rootDir, "public", "games");
  if (!existsSync(src)) return;
  cpSync(src, dest, { recursive: true });
}

function gamesSyncPlugin(rootDir: string): Plugin {
  return {
    name: "sync-root-games-to-public",
    buildStart() {
      writeGameIdsManifest(rootDir);
    },
    configureServer(server) {
      syncRootGamesToPublic(rootDir);
      writeGameIdsManifest(rootDir);
      const gamesDir = path.resolve(rootDir, "games");
      if (!existsSync(gamesDir)) return;
      const underGames = (file: string) => {
        const f = path.resolve(file);
        const g = path.resolve(gamesDir);
        return f === g || f.startsWith(`${g}${path.sep}`);
      };
      const sync = () => {
        syncRootGamesToPublic(rootDir);
        writeGameIdsManifest(rootDir);
      };
      server.watcher.on("change", (file) => {
        if (underGames(file)) sync();
      });
      server.watcher.on("add", (file) => {
        if (underGames(file)) sync();
      });
      server.watcher.on("unlink", (file) => {
        if (underGames(file)) sync();
      });
    },
    closeBundle() {
      const gamesDir = path.resolve(rootDir, "games");
      if (!existsSync(gamesDir)) return;
      const outGames = path.resolve(rootDir, "dist/public/games");
      cpSync(gamesDir, outGames, { recursive: true });
    },
  };
}

export default defineConfig({
  base: basePath,
  plugins: [
    gamesSyncPlugin(path.resolve(import.meta.dirname)),
    react(),
    tailwindcss(),
    runtimeErrorOverlay(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
      "@assets": path.resolve(import.meta.dirname, "public"),
    },
    dedupe: ["react", "react-dom"],
  },
  root: path.resolve(import.meta.dirname),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
  },
  server: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
    fs: {
      strict: true,
      deny: ["**/.*"],
    },
  },
  preview: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
  },
});
